package com.mediabuzz.beans;
// Generated 11 mars 2016 15:25:13 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "mediabuzz")
public class Comment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6706260574071338215L;
	private int publicationId;
	private Publication publicationByPublicationId;
	private Publication publicationByPublicationId1;
	private String commentContent;

	public Comment() {
	}

	public Comment(Publication publicationByPublicationId, Publication publicationByPublicationId1,
			String commentContent) {
		this.publicationByPublicationId = publicationByPublicationId;
		this.publicationByPublicationId1 = publicationByPublicationId1;
		this.commentContent = commentContent;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "publicationByPublicationId") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "publication_id", unique = true, nullable = false)
	public int getPublicationId() {
		return this.publicationId;
	}

	public void setPublicationId(int publicationId) {
		this.publicationId = publicationId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Publication getPublicationByPublicationId() {
		return this.publicationByPublicationId;
	}

	public void setPublicationByPublicationId(Publication publicationByPublicationId) {
		this.publicationByPublicationId = publicationByPublicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publication_id_1", nullable = false)
	public Publication getPublicationByPublicationId1() {
		return this.publicationByPublicationId1;
	}

	public void setPublicationByPublicationId1(Publication publicationByPublicationId1) {
		this.publicationByPublicationId1 = publicationByPublicationId1;
	}

	@Column(name = "comment_content", nullable = false)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

}
