package com.mediabuzz.beans;
// Generated 11 mars 2016 15:25:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state", catalog = "mediabuzz", uniqueConstraints = @UniqueConstraint(columnNames = "state_name") )
public class State implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1329169494097174321L;
	private Integer stateId;
	private String stateName;
	private Set<Publication> publications = new HashSet<Publication>(0);
	private Set<User> users = new HashSet<User>(0);

	public State() {
	}

	public State(String stateName) {
		this.stateName = stateName;
	}

	public State(String stateName, Set<Publication> publications, Set<User> users) {
		this.stateName = stateName;
		this.publications = publications;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "state_id", unique = true, nullable = false)
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "state_name", unique = true, nullable = false, length = 50)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<Publication> getPublications() {
		return this.publications;
	}

	public void setPublications(Set<Publication> publications) {
		this.publications = publications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
