package com.mediabuzz.beans;
// Generated 11 mars 2016 15:25:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "mediabuzz")
public class Tag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2966080068789890844L;
	private Integer tagId;
	private String tagName;
	private Set<Vote> votes = new HashSet<Vote>(0);
	private Set<Publication> publications = new HashSet<Publication>(0);

	public Tag() {
	}

	public Tag(String tagName) {
		this.tagName = tagName;
	}

	public Tag(String tagName, Set<Vote> votes, Set<Publication> publications) {
		this.tagName = tagName;
		this.votes = votes;
		this.publications = publications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tag_id", unique = true, nullable = false)
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	@Column(name = "tag_name", nullable = false, length = 25)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
	public Set<Vote> getVotes() {
		return this.votes;
	}

	public void setVotes(Set<Vote> votes) {
		this.votes = votes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "define", catalog = "mediabuzz", joinColumns = {
			@JoinColumn(name = "tag_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "publication_id", nullable = false, updatable = false) })
	public Set<Publication> getPublications() {
		return this.publications;
	}

	public void setPublications(Set<Publication> publications) {
		this.publications = publications;
	}

}
