package com.mediabuzz.beans;
// Generated 11 mars 2016 15:25:13 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mediabuzz", uniqueConstraints = @UniqueConstraint(columnNames = "user_login") )
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6451327207687761087L;
	private Integer userId;
	private State state;
	private String userLogin;
	private String userPassword;
	private boolean userRole;
	private Set<Vote> votes = new HashSet<Vote>(0);
	private Set<Publication> publications = new HashSet<Publication>(0);

	public User() {
	}

	public User(State state, String userLogin, String userPassword, boolean userRole) {
		this.state = state;
		this.userLogin = userLogin;
		this.userPassword = userPassword;
		this.userRole = userRole;
	}

	public User(State state, String userLogin, String userPassword, boolean userRole, Set<Vote> votes,
			Set<Publication> publications) {
		this.state = state;
		this.userLogin = userLogin;
		this.userPassword = userPassword;
		this.userRole = userRole;
		this.votes = votes;
		this.publications = publications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_id", nullable = false)
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "user_login", unique = true, nullable = false, length = 20)
	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "user_password", nullable = false, length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_role", nullable = false)
	public boolean isUserRole() {
		return this.userRole;
	}

	public void setUserRole(boolean userRole) {
		this.userRole = userRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Vote> getVotes() {
		return this.votes;
	}

	public void setVotes(Set<Vote> votes) {
		this.votes = votes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Publication> getPublications() {
		return this.publications;
	}

	public void setPublications(Set<Publication> publications) {
		this.publications = publications;
	}

}
